### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by annadecarle** [annadecarle/web-design-2-independent-project#11]
Hi @thatkidmadrid
I'm having an issue setting up my favicon. I created one, got it to display on my webpage, but markbot is still giving me the issue that missing the 16x16 version and the 32x32 version in my favicon.ico. How do I properly place my favicon in my website? I can't seem to set the files up correctly.

**Comment by thatkidmadrid** [comment]
https://favicon.io/favicon-converter/

We covered in class that this converter will create a proper .ico file that includes those sizes that markbot is looking for

Here is the written lesson if you need help setting it up in your html, but it sounds like you're just missing the other sizes in your .ico file

**Comment by annadecarle** [comment]
Thank you, that was very helpful.
